name: 9cc test
on: [push]
jobs:
  test:
    name: 9cc test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: prepare
        run: sudo apt-get update && sudo apt-get install -y gcc make git binutils libc6-dev
      - name: run test
        run: |
          cd 9cc && make test
